package:
  image: debian:sid
  script:
    - apt-get update
    - apt-get build-dep -y ./
    - dpkg-buildpackage -us -uc

.test simple: &TEST-SIMPLE
  variables:
    LOGNAME: root
  script:
    - cd tests && bats scripts/default
  artifacts:
    paths:
      - tests/log
      - tests/output
    when: always

.test debian: &TEST-DEBIAN
  before_script:
    - apt-get update > /dev/null
    - DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends bats curl git rsync stunnel > /dev/null

.test debian busybox: &TEST-DEBIAN-BUSYBOX
  before_script:
    - apt-get update > /dev/null
    - DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends bats busybox curl git rsync stunnel > /dev/null
    - busybox --install -s /usr/local/bin

.test redhat: &TEST-REDHAT
  before_script:
    - yum install -y epel-release > /dev/null
    - yum install -y bats curl git rsync stunnel > /dev/null

test stretch:
  <<: *TEST-DEBIAN
  <<: *TEST-SIMPLE
  image: debian:stretch

test basic:
  <<: *TEST-DEBIAN-BUSYBOX
  <<: *TEST-SIMPLE
  image: debian:stretch

test centos6:
  <<: *TEST-REDHAT
  <<: *TEST-SIMPLE
  image: centos:centos6

test centos7:
  <<: *TEST-REDHAT
  <<: *TEST-SIMPLE
  image: centos:centos7
